-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Juniper.Object exposing (..)


type Comment
    = Comment


type Job
    = Job


type Story
    = Story
