-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Juniper.Query exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Juniper.InputObject
import Juniper.Interface
import Juniper.Object
import Juniper.Scalar
import Juniper.ScalarCodecs
import Juniper.Union


type alias TopItemsOptionalArguments =
    { limit : OptionalArgument Int }


topItems :
    (TopItemsOptionalArguments -> TopItemsOptionalArguments)
    -> SelectionSet decodesTo Juniper.Union.Item
    -> SelectionSet (List decodesTo) RootQuery
topItems fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { limit = Absent }

        optionalArgs____ =
            [ Argument.optional "limit" filledInOptionals____.limit Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "topItems" optionalArgs____ object____ (Basics.identity >> Decode.list)


type alias ItemByIdRequiredArguments =
    { id : Int }


itemById :
    ItemByIdRequiredArguments
    -> SelectionSet decodesTo Juniper.Union.Item
    -> SelectionSet (Maybe decodesTo) RootQuery
itemById requiredArgs____ object____ =
    Object.selectionForCompositeField "itemById" [ Argument.required "id" requiredArgs____.id Encode.int ] object____ (Basics.identity >> Decode.nullable)
