-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Juniper.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Juniper.Scalar exposing (defaultCodecs)


type alias DateTime =
    Juniper.Scalar.DateTime


type alias Id =
    Juniper.Scalar.Id


type alias NaiveDateTime =
    Juniper.Scalar.NaiveDateTime


codecs : Juniper.Scalar.Codecs DateTime Id NaiveDateTime
codecs =
    Juniper.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecId = defaultCodecs.codecId
        , codecNaiveDateTime = defaultCodecs.codecNaiveDateTime
        }
