-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Juniper.Object.Job exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Juniper.InputObject
import Juniper.Interface
import Juniper.Object
import Juniper.Scalar
import Juniper.ScalarCodecs
import Juniper.Union


{-| The item's unique id.
-}
id : SelectionSet Int Juniper.Object.Job
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The story's score, or the votes for a pollopt.
-}
score : SelectionSet Int Juniper.Object.Job
score =
    Object.selectionForField "Int" "score" [] Decode.int


{-| The job text. HTML.
-}
text : SelectionSet (Maybe String) Juniper.Object.Job
text =
    Object.selectionForField "(Maybe String)" "text" [] (Decode.string |> Decode.nullable)


{-| Creation date of the item, in Unix Time.
-}
time : SelectionSet Int Juniper.Object.Job
time =
    Object.selectionForField "Int" "time" [] Decode.int


{-| The title of the job.
-}
title : SelectionSet String Juniper.Object.Job
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| The URL of the story.
-}
url : SelectionSet (Maybe String) Juniper.Object.Job
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)
