-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Juniper.Object.Story exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Juniper.InputObject
import Juniper.Interface
import Juniper.Object
import Juniper.Scalar
import Juniper.ScalarCodecs
import Juniper.Union


id : SelectionSet Int Juniper.Object.Story
id =
    Object.selectionForField "Int" "id" [] Decode.int


totalCommentCount : SelectionSet Int Juniper.Object.Story
totalCommentCount =
    Object.selectionForField "Int" "totalCommentCount" [] Decode.int


by : SelectionSet String Juniper.Object.Story
by =
    Object.selectionForField "String" "by" [] Decode.string


kids : SelectionSet (Maybe (List Int)) Juniper.Object.Story
kids =
    Object.selectionForField "(Maybe (List Int))" "kids" [] (Decode.int |> Decode.list |> Decode.nullable)


score : SelectionSet Int Juniper.Object.Story
score =
    Object.selectionForField "Int" "score" [] Decode.int


title : SelectionSet String Juniper.Object.Story
title =
    Object.selectionForField "String" "title" [] Decode.string


url : SelectionSet (Maybe String) Juniper.Object.Story
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


text : SelectionSet (Maybe String) Juniper.Object.Story
text =
    Object.selectionForField "(Maybe String)" "text" [] (Decode.string |> Decode.nullable)


time : SelectionSet Juniper.ScalarCodecs.DateTime Juniper.Object.Story
time =
    Object.selectionForField "ScalarCodecs.DateTime" "time" [] (Juniper.ScalarCodecs.codecs |> Juniper.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


children :
    SelectionSet decodesTo Juniper.Union.Item
    -> SelectionSet (List decodesTo) Juniper.Object.Story
children object____ =
    Object.selectionForCompositeField "children" [] object____ (Basics.identity >> Decode.list)


descendants :
    SelectionSet decodesTo Juniper.Union.Item
    -> SelectionSet (List decodesTo) Juniper.Object.Story
descendants object____ =
    Object.selectionForCompositeField "descendants" [] object____ (Basics.identity >> Decode.list)


safeText : SelectionSet String Juniper.Object.Story
safeText =
    Object.selectionForField "String" "safeText" [] Decode.string


humanTime : SelectionSet String Juniper.Object.Story
humanTime =
    Object.selectionForField "String" "humanTime" [] Decode.string
